language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.5
before_script:
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
